name: Tests on Windows

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master
      - github-actions-test
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2016]
        node: [10]

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master

      - name: Install Global Dependencies
        run: choco install microsoft-build-tools-2013
      
      - name: Install Yarn
        run: npm install yarn -g

      - name: Install
        run: yarn install
        
      - name: Test
        run: yarn test
